# Generated by Django 4.2.6 on 2023-10-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatingadmin',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
