# Generated by Django 4.2.6 on 2023-11-24 12:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_creatingadmin_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('billing_email', models.EmailField(max_length=254, null=True)),
                ('payment_mode', models.CharField(max_length=100, null=True)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('current_coordinates', models.JSONField(null=True)),
                ('destination_location', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_coordinates', models.JSONField(blank=True, null=True)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('ride_status', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('request_id', models.CharField(max_length=100, null=True)),
                ('link', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LimoDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_profilepic', models.ImageField(default='driver/profile_pic/Dpic.png', upload_to='driver/profile_pic', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('otp', models.CharField(max_length=4)),
                ('password', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('car_name', models.CharField(max_length=100, null=True)),
                ('year_vehicle', models.CharField(max_length=100, null=True)),
                ('license_plate', models.CharField(max_length=100, null=True)),
                ('car_image', models.ImageField(null=True, upload_to='driver/car_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('driving_license', models.ImageField(null=True, upload_to='driver/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('license_plate_image', models.ImageField(null=True, upload_to='driver/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('car_insurance_image', models.ImageField(null=True, upload_to='driver/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(default='pending', max_length=15)),
                ('active', models.CharField(default='offline', max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('current_coordinates', models.JSONField(null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('total_earning', models.FloatField(default=0.0)),
                ('wallet', models.CharField(default='0', max_length=100)),
                ('total_booking', models.FloatField(default=0)),
                ('player_id', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LimoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profilepic', models.ImageField(default='driver/profile_pic/Upic.jpg', upload_to='driver/profile_pic', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('confirm_password', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('player_id', models.CharField(max_length=50, null=True)),
                ('otp', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravellingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user_profilepic', models.ImageField(default='driver/profile_pic/Upic.jpg', upload_to='driver/profile_pic', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_location', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_email', models.EmailField(max_length=254, null=True)),
                ('driver_profilepic', models.ImageField(default='driver/profile_pic/Dpic.png', upload_to='driver/profile_pic', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('price', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='creatingadmin',
            old_name='admin_pnumber',
            new_name='admin_city',
        ),
        migrations.RemoveField(
            model_name='creatingadmin',
            name='approved',
        ),
        migrations.AddField(
            model_name='creatingadmin',
            name='admin_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creatingadmin',
            name='status',
            field=models.CharField(default='Unapproved', max_length=10),
        ),
        migrations.AddField(
            model_name='creatingadmin',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.limodriver')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.limouser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True, default='', null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.limouser')),
            ],
        ),
        migrations.CreateModel(
            name='DriverReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('review', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.limodriver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.limouser')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.limouser')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDriverToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.limodriver')),
            ],
        ),
    ]
